[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"
tokio = { version = "1", feature = ["full"] }
actix-cors = "0.6.4"
